---
title: "Black Owned Businesses in Eugene"
output:
  html_document:
    toc: true
    toc_float: true

---
```{r include=FALSE}
library(pacman)
p_load(tidyverse,kableExtra, rmdformats)
library(readr)
bbe <- read_csv("Black Businesses to Support in Eugene - Type.csv")
bbe$Name <- paste0("[", bbe$Name, "](",bbe$`Instagram Link`, ")")
```

## **Food and Dining**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "food.dining")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)
```

## **Hair Care and Beauty**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "haircare.beauty")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Cannabis and Vape**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "cannabis.vape")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Retail**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "retail")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Home Decor**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "home.decor")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)
```

## **Health, Fitness, and Athletics**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "health")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Music and Dance**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "music")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Auto**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "auto")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Animal Support**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "animal")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Non-profits**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "nonprofits")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Authors**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "authors")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Photography/Videography**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "photography")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Officiant**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "officiant")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Landscaping**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "landscaping")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```

## **Art**
```{r echo=FALSE, results='asis'}
library(knitr)
kable(filter(bbe, Type == "art")[,2:3], col.names = NULL)%>%
  kable_styling(bootstrap_options = c("striped", "hover","responsive"))%>%
    column_spec(1,width = "4.5cm", bold = T)

```